### ISSUE TITLE
Form is not persistent across page reloads

### ISSUE THREAD

**Issue by lordkada** [vivekmunde/EmberJSChallenge#1]
If I hit the "refresh" button, the input form cleans up

**Comment by vivekmunde** [comment]
My bad. I will use local storage to make sure the input persists on page reloads. I will fix this by tomorrow end of the day for sure. 

Thanks

**Comment by lordkada** [comment]
Ok

**Comment by vivekmunde** [comment]
Fixed

**Comment by lordkada** [comment]
Ok, it works now!

I'd move the observer (newItemChanged in services/appliances-list.js) to the 'appliance-new' component  because I like the idea to have the "view observer" tied to the component... Then this observer could delegate the "save" operation to the service.

See my #4

**Comment by vivekmunde** [comment]
Yes, got it. Component may or may not use the service object directly. It can have its wrapper on top of the new item returned from service. Also, component is the action taker on the model. So its better to have the observers on the component and pass the item to service to preserve it. 

One query, I think the service method 'setNewItem' should set the newItem (within the service) also along with preserving in the sessionStorage. So if in case if the component is creating a copy of the newItem returned from the service and using it then its better to set the newItem value along with the sessionStorage. Please provide your input on this.
------
setNewItem(appliance) {
        ==>> this.set('newItem', appliance); /* setting the newItem property value */

        /* Update the session storage */
        window.sessionStorage.setItem('appliances.new', JSON.stringify(appliance));
    }
------

Done and checked in.

**Comment by lordkada** [comment]
Yep,
I agree..
;-)
