### ISSUE TITLE
Unused appliances data in routes/appliances.js 

### ISSUE THREAD

**Issue by lordkada** [vivekmunde/EmberJSChallenge#2]
Are they used somewhere or it is old pending stuffs?

**Comment by vivekmunde** [comment]
Is it regarding the existing two records? If yes then they are default and are hard saved in the JSON for default display. I will remove them also in my tomorrow's fix. 

Thanks

**Comment by lordkada** [comment]
Ok ;-)

**Comment by vivekmunde** [comment]
default appliances removed

**Comment by vivekmunde** [comment]
Actually it was a misunderstanding from my side. I thought "data persistence across page reloads" means on route changes, templates reloads. That was implemented by me previously. 

Now the data gets persisted on page reloads/refresh.

**Comment by lordkada** [comment]
I meant stuffs like:
`
    model: 'Msuhfei 12',
    description: 'Jjsdh kuhsd Ku sdj ds asuhdkajs au adh jgef ajmsd jhsgd fjhsdgf uh gsdf jagdfjahsfd jagfj ashgajhsg dsjh ahsgj dhsa jhgd ajhs'
` 
from `routes/appliances.js`

It looks that you're not using them... 
;-)

**Comment by vivekmunde** [comment]
:) ... my bad ... had put it for some testing at the start ... removed now

**Comment by lordkada** [comment]
Ok

(we could also remove the whole file.. but don't worry.. I don't ask to do that... ;-) )
